### ISSUE TITLE
can't generate new project

### ISSUE THREAD

**Issue by dehuszar** [Appyre/driven-cli#2]
Hey there,

I just attempted to generate a new project using driven and saw the following error:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'escape-string-regexp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dehuszar/.nvm/node_global/lib/node_modules/driven-cli/node_modules/chalk/index.js:2:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

I would like to give this a whirl on a current project if there's a quick solution.

Thanks!

**Comment by dehuszar** [comment]
Adding on to the above, modules 'escape-string-regex', 'rimraf', and strip-ansi' had to be globally installed before I could finish an attempt at generating a new project.  The directory was created, but the error `Unknown blueprint: ng2` resulted.

The command _did_ create a new folder, but the folder was empty.

**Comment by runspired** [comment]
@dehuszar most the work on this is still on my machine, and I haven't gotten enough time to push it up.
